try {
    throw new Error('An error occured');
} catch (e) {
    console.log(e);
}

